apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: k8s-101
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 30080
      protocol: TCP
  selector:
    app: nginx
